### ISSUE TITLE
How should we manage PHP version support?

### ISSUE THREAD

**Issue by RobjS** [dxw/iguana#33]
We are currently doing this by setting the config/platform setting in composer.json: https://github.com/dxw/iguana/blob/7f37f740f6eba8573c5fa2807f169d98291e6491/composer.json#L8

It strikes me that this is a misuse of this config, as it should really only be applied on a project as a whole (to ensure that it installs the correct versions of its dependencies), rather than in a library that could be re-used across projects. This is particularly the case as some conventions suggest that changing PHP version support is not a breaking change (e.g. see https://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html), but the way we manage it means that is not necessarily the case.

An example of how changing the PHP config/platform version could lead to a breaking change:

- A user is running Iguana v1.1.1 on a server that runs PHP 7.0.
- We bump the config/platform setting to PHP 7.2, update the composer dependencies and release this as v1.2.
- The user runs `composer update` on their local machine, and it pulls Iguana v1.2, with dependencies that only work on PHP 7.2 upwards. 
- They deploy this code to their server that runs PHP 7.0, and it fails.

Given that there are people out there on non-dxw servers running Iguana (e.g. former clients), it seems like this is a real possibility.

I think this method of managing PHP versions (i.e. via the config/platform setting) is really a mitigation for the fact that our projects have multiple `composer.json` files scattered across them, and the only way we have of ensuring they're all running the same PHP version is by specifying the platform in each separate `composer.json`. Ideally, there would just be one central `composer.json` per project, where we could set a config/platform PHP version, and in shared libraries like this, we would drop support for old PHP versions by specifying a PHP version in the composer requirements (therefore making it a non-breaking change, as a user running an older PHP version just wouldn't get newer versions of the package) rather than in config/platform.

However, that doesn't seem a likely scenario given our current build/deployment process. So should we just accept we're going to set the PHP version in config/platform, and make it a major version change whenever we bump the version? Or is there a better option I'm not thinking of?

**Comment by mallorydxw** [comment]
Resolved by: https://github.com/dxw/iguana/pull/35
